meta-aspeed: linux-yocto-fitimage: Add RSA signing keys
The linux-yocto-fitimage recipe uses the kernel-fit-image.bbclass which
requires RSA key files to be present in UNPACKDIR when UBOOT_SIGN_ENABLE
is set. These keys are used for FIT image signature validation.

The RSA key files (rsa_oem_fitimage_key.key and rsa_oem_fitimage_key.crt)
were previously only provided by linux-aspeed.inc, but linux-yocto-fitimage
doesn't inherit from that file. This caused build failures on machines like
p10bmc that enable FIT image signing.

Add a bbappend to provide these key files to the linux-yocto-fitimage
recipe by symlinking to the existing keys in linux-aspeed.

This fixes the error:
  ERROR: linux-yocto-fitimage-1.0-r0 do_compile:
  /path/to/sources/rsa_oem_fitimage_key.key or .crt does not exist

Change-Id: Id85db8951e95aa9d79d2a87465e7c97131a77d28
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>